<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SubCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_categories')->insert([
            ['category_id' => 1,
                'sub_category_name' => 'Tư liệu',
                'sub_cate_slug' => 'tu-lieu',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 1,
                'sub_category_name' => 'Phân tích',
                'sub_cate_slug' => 'phan-tich',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 1,
                'sub_category_name' => 'Người Việt 5 châu',
                'sub_cate_slug' => 'nguoi-viet-5-chau',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 1,
                'sub_category_name' => 'Quân sự',
                'sub_cate_slug' => 'quan-su',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 2,
                'sub_category_name' => 'Doanh nghiệp',
                'sub_cate_slug' => 'doanh-nghiep',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 2,
                'sub_category_name' => 'Bất động sản',
                'sub_cate_slug' => 'bat-dong-san',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 2,
                'sub_category_name' => 'Ebank',
                'sub_cate_slug' => 'ebank',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 2,
                'sub_category_name' => 'Chứng khoán',
                'sub_cate_slug' => 'chung-khoan',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 2,
                'sub_category_name' => 'Thương mại điện tử',
                'sub_cate_slug' => 'thuong-mai-dien-tu',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 3,
                'sub_category_name' => 'Giới sao',
                'sub_cate_slug' => 'gioi-sao',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 3,
                'sub_category_name' => 'Thời trang',
                'sub_cate_slug' => 'thoi-trang',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 3,
                'sub_category_name' => 'Phim',
                'sub_cate_slug' => 'phim',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 3,
                'sub_category_name' => 'Truyền hình',
                'sub_cate_slug' => 'truyen-hinh',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 3,
                'sub_category_name' => 'Nhạc',
                'sub_cate_slug' => 'nhac',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 4,
                'sub_category_name' => 'Tuyển sinh',
                'sub_cate_slug' => 'tuyen-sinh',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 4,
                'sub_category_name' => 'Du học',
                'sub_cate_slug' => 'du-hoc',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 5,
                'sub_category_name' => 'Môi trường',
                'sub_cate_slug' => 'moi-truong',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 5,
                'sub_category_name' => 'Công nghệ mới',
                'sub_cate_slug' => 'cong-nghe-moi',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 5,
                'sub_category_name' => 'Chuyện lạ',
                'sub_cate_slug' => 'chuyen-la',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 6,
                'sub_category_name' => 'Đời sống số',
                'sub_cate_slug' => 'doi-song-so',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 6,
                'sub_category_name' => 'Sản phẩm',
                'sub_cate_slug' => 'san-pham',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 6,
                'sub_category_name' => 'Điện tử gia dụng',
                'sub_cate_slug' => 'dien-tu-gia-dung',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 7,
                'sub_category_name' => 'Ngoại hạng Anh',
                'sub_cate_slug' => 'ngoai-hang-anh',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['category_id' => 7,
                'sub_category_name' => 'Laliga',
                'sub_cate_slug' => 'laliga',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')]
        ]);
    }
}
